export const locales = ["pt", "en", "es", "nl"] as const;
export type Locale = (typeof locales)[number];

export const localeOptions: Record<Locale, { flag: string; short: string; label: string }> = {
  pt: { flag: "/flag-pt.svg", short: "PT", label: "Português" },
  en: { flag: "/flag-en.svg", short: "EN", label: "English" },
  es: { flag: "/flag-es.svg", short: "ES", label: "Español" },
  nl: { flag: "/flag-nl.svg", short: "NL", label: "Nederlands" },
};

type ServiceCopy = {
  productId: string;
  title: string;
  text: string;
  duration: string;
  price: string;
  badge: string;
};

const ptServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Primeira Consulta Online",
    text: "Encontro inicial para compreender a sua situação e definir um plano personalizado.",
    duration: "1 hora · online",
    price: "69 €",
    badge: "Novos clientes",
  },
  {
    productId: "energy-cleansing",
    title: "Limpeza Energética & Espiritual",
    text: "Restauração vibracional, limpeza de cargas e harmonização da aura e dos corpos sutis.",
    duration: "Sessão à distância",
    price: "114,99 €",
    badge: "Restauro",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Limpeza + 1ª Consulta",
    text: "Opção indicada para quem ainda precisa da consulta inicial antes da limpeza energética.",
    duration: "Consulta + tratamento",
    price: "150,99 €",
    badge: "Pacote inicial",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarô & Leitura de Campo",
    text: "Leitura para questões específicas, com orientação espiritual por chamada online.",
    duration: "1 hora",
    price: "105,99 €",
    badge: "Orientação",
  },
  {
    productId: "chakra-unblocking",
    title: "Restauração Integral dos Chakras",
    text: "Cuidado focado no equilíbrio energético, conexão corporal e estabilidade interior.",
    duration: "À distância",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas e Bloqueios",
    text: "Sessão intensiva para padrões profundos, bloqueios emocionais e desorientação energética.",
    duration: "Sessão intensiva",
    price: "204,99 €",
    badge: "Intensivo",
  },
  {
    productId: "depression-support",
    title: "Tratamento para Depressão",
    text: "Apoio energético intensivo à distância, com primeira consulta e acompanhamento estruturado.",
    duration: "30 dias",
    price: "267,99 €",
    badge: "Apoio",
  },
  {
    productId: "environment-harmonization",
    title: "Harmonização de Ambientes",
    text: "Limpeza e equilíbrio energético para residências ou espaços que estejam carregados.",
    duration: "Até 3 residências",
    price: "294 €",
    badge: "Ambientes",
  },
];

const enServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "First Online Consultation",
    text: "Initial meeting to understand your situation and define a personalised plan.",
    duration: "1 hour · online",
    price: "69 €",
    badge: "New clients",
  },
  {
    productId: "energy-cleansing",
    title: "Energetic & Spiritual Cleansing",
    text: "Vibrational restoration, cleansing of heavy energy and harmonisation of the aura and subtle bodies.",
    duration: "Remote session",
    price: "114.99 €",
    badge: "Restore",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Cleansing + First Consultation",
    text: "Recommended for those who still need the initial consultation before energetic cleansing.",
    duration: "Consultation + treatment",
    price: "150.99 €",
    badge: "Starter pack",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot & Field Reading",
    text: "Reading for specific questions with spiritual guidance through an online call.",
    duration: "1 hour",
    price: "105.99 €",
    badge: "Guidance",
  },
  {
    productId: "chakra-unblocking",
    title: "Integral Chakra Restoration",
    text: "Care focused on energetic balance, body connection and inner stability.",
    duration: "Remote",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas and Blockages",
    text: "Intensive session for deep patterns, emotional blocks and energetic disorientation.",
    duration: "Intensive session",
    price: "204.99 €",
    badge: "Intensive",
  },
  {
    productId: "depression-support",
    title: "Depression Support Treatment",
    text: "Intensive remote energetic support with first consultation and structured follow-up.",
    duration: "30 days",
    price: "267.99 €",
    badge: "Support",
  },
  {
    productId: "environment-harmonization",
    title: "Environment Harmonisation",
    text: "Energetic cleansing and balancing for homes or spaces that feel heavy.",
    duration: "Up to 3 homes",
    price: "294 €",
    badge: "Spaces",
  },
];

const esServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Primera Consulta Online",
    text: "Encuentro inicial para comprender tu situación y definir un plan personalizado.",
    duration: "1 hora · online",
    price: "69 €",
    badge: "Nuevos clientes",
  },
  {
    productId: "energy-cleansing",
    title: "Limpieza Energética y Espiritual",
    text: "Restauración vibracional, limpieza de cargas y armonización del aura y cuerpos sutiles.",
    duration: "Sesión a distancia",
    price: "114,99 €",
    badge: "Restauración",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Limpieza + Primera Consulta",
    text: "Opción indicada para quien aún necesita la consulta inicial antes de la limpieza energética.",
    duration: "Consulta + tratamiento",
    price: "150,99 €",
    badge: "Pack inicial",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot y Lectura de Campo",
    text: "Lectura para preguntas específicas con orientación espiritual por llamada online.",
    duration: "1 hora",
    price: "105,99 €",
    badge: "Orientación",
  },
  {
    productId: "chakra-unblocking",
    title: "Restauración Integral de Chakras",
    text: "Cuidado enfocado en equilibrio energético, conexión corporal y estabilidad interior.",
    duration: "A distancia",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas y Bloqueos",
    text: "Sesión intensiva para patrones profundos, bloqueos emocionales y desorientación energética.",
    duration: "Sesión intensiva",
    price: "204,99 €",
    badge: "Intensivo",
  },
  {
    productId: "depression-support",
    title: "Tratamiento para Depresión",
    text: "Apoyo energético intensivo a distancia, con primera consulta y seguimiento estructurado.",
    duration: "30 días",
    price: "267,99 €",
    badge: "Apoyo",
  },
  {
    productId: "environment-harmonization",
    title: "Armonización de Ambientes",
    text: "Limpieza y equilibrio energético para residencias o espacios que se sienten cargados.",
    duration: "Hasta 3 residencias",
    price: "294 €",
    badge: "Ambientes",
  },
];

const nlServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Eerste Online Consult",
    text: "Eerste gesprek om jouw situatie te begrijpen en een persoonlijk plan te bepalen.",
    duration: "1 uur · online",
    price: "69 €",
    badge: "Nieuwe cliënten",
  },
  {
    productId: "energy-cleansing",
    title: "Energetische & Spirituele Reiniging",
    text: "Vibrationeel herstel, reiniging van zware energie en harmonisatie van aura en subtiele lichamen.",
    duration: "Sessie op afstand",
    price: "114,99 €",
    badge: "Herstel",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Reiniging + Eerste Consult",
    text: "Aangeraden voor wie eerst een kennismakingsconsult nodig heeft voor de energetische reiniging.",
    duration: "Consult + behandeling",
    price: "150,99 €",
    badge: "Startpakket",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot & Veldlezing",
    text: "Lezing voor specifieke vragen met spirituele begeleiding via online gesprek.",
    duration: "1 uur",
    price: "105,99 €",
    badge: "Begeleiding",
  },
  {
    productId: "chakra-unblocking",
    title: "Integrale Chakra Herstelling",
    text: "Zorg gericht op energetisch evenwicht, lichaamsverbinding en innerlijke stabiliteit.",
    duration: "Op afstand",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Trauma's en Blokkades",
    text: "Intensieve sessie voor diepe patronen, emotionele blokkades en energetische desoriëntatie.",
    duration: "Intensieve sessie",
    price: "204,99 €",
    badge: "Intensief",
  },
  {
    productId: "depression-support",
    title: "Behandeling bij Depressie",
    text: "Intensieve energetische ondersteuning op afstand, met eerste consult en gestructureerde opvolging.",
    duration: "30 dagen",
    price: "267,99 €",
    badge: "Steun",
  },
  {
    productId: "environment-harmonization",
    title: "Harmonisatie van Ruimtes",
    text: "Energetische reiniging en balans voor woningen of ruimtes die zwaar aanvoelen.",
    duration: "Tot 3 woningen",
    price: "294 €",
    badge: "Ruimtes",
  },
];

type ServiceTuple = [productId: string, title: string, text: string, duration: string, price: string, badge: string];

const additionalServiceCopies: Record<Locale, ServiceTuple[]> = {
  pt: [
    ["environment-harmonization-3-homes", "Harmonização de Ambientes · 3 Residências", "Pacote para até três residências ou espaços que precisam de equilíbrio.", "Até 3 residências", "294 €", "Pacote"],
    ["tarot-field-reading-2h", "Tarô e Leitura de Campo · 2 horas", "Leitura estendida para perguntas mais profundas e campo energético.", "2 horas", "195,99 €", "Estendida"],
    ["depression-support-3-months", "Tratamento para Depressão · 3 meses", "Acompanhamento energético contínuo durante três meses.", "3 meses contínuos", "690 €", "Contínuo"],
    ["migraine-support", "Tratamento Enxaqueca Crônica + Consulta", "Apoio energético com consulta para casos de enxaqueca crônica.", "30 dias", "267,99 €", "Apoio"],
    ["migraine-support-3-months", "Tratamento Enxaqueca Crônica · 3 meses", "Acompanhamento energético contínuo para enxaqueca crônica.", "3 meses contínuos", "690 €", "Contínuo"],
    ["terminal-transition-support", "Apoio Fase Terminal e Transição + Consulta", "Acolhimento energético em processos delicados de transição.", "Consulta + apoio", "150,99 €", "Transição"],
    ["guided-healing-movement", "Movimento de Cura Guiada com Equipe Seriana", "Sessão guiada de cura energética com preparação e formulário obrigatório.", "1 hora", "114,99 €", "Cura guiada"],
    ["mental-relief", "Alívio Mental Imediato e Confusão Mental", "Sessão para clareza, leveza mental e organização energética.", "1 hora", "105,99 €", "Clareza"],
    ["trauma-intensive-3", "3 Sessões Intensivas: Traumas, Bloqueios e Libertações", "Pacote de três sessões intensivas de duas horas.", "3 sessões · 2 horas cada", "555,99 €", "Pacote"],
    ["trauma-intensive-6", "6 Sessões Intensivas: Traumas, Bloqueios e Libertações", "Plano completo de seis sessões intensivas de duas horas.", "6 sessões · 2 horas cada", "996,99 €", "Acompanhamento"],
  ],
  en: [
    ["environment-harmonization-3-homes", "Environment Harmonisation · 3 Homes", "Package for up to three homes or spaces that need energetic balance.", "Up to 3 homes", "294 €", "Package"],
    ["tarot-field-reading-2h", "Tarot and Field Reading · 2 hours", "Extended reading for deeper questions and the energetic field.", "2 hours", "195.99 €", "Extended"],
    ["depression-support-3-months", "Depression Support Treatment · 3 months", "Continuous energetic support over three months.", "3 continuous months", "690 €", "Ongoing"],
    ["migraine-support", "Chronic Migraine Support + Consultation", "Energetic support with consultation for chronic migraine.", "30 days", "267.99 €", "Support"],
    ["migraine-support-3-months", "Chronic Migraine Support · 3 months", "Continuous energetic support for chronic migraine.", "3 continuous months", "690 €", "Ongoing"],
    ["terminal-transition-support", "End-of-Life and Transition Support + Consultation", "Energetic care during delicate transition processes.", "Consultation + support", "150.99 €", "Transition"],
    ["guided-healing-movement", "Guided Healing Movement with the Seriana Team", "Guided energetic healing session with preparation and a required form.", "1 hour", "114.99 €", "Guided healing"],
    ["mental-relief", "Immediate Mental Relief and Mental Confusion", "Session for clarity, mental lightness and energetic organisation.", "1 hour", "105.99 €", "Clarity"],
    ["trauma-intensive-3", "3 Intensive Sessions: Trauma, Blockages and Release", "Package of three intensive two-hour sessions.", "3 sessions · 2 hours each", "555.99 €", "Package"],
    ["trauma-intensive-6", "6 Intensive Sessions: Trauma, Blockages and Release", "Complete plan of six intensive two-hour sessions.", "6 sessions · 2 hours each", "996.99 €", "Follow-up"],
  ],
  es: [
    ["environment-harmonization-3-homes", "Armonización de Ambientes · 3 Residencias", "Paquete para hasta tres residencias o espacios que necesitan equilibrio.", "Hasta 3 residencias", "294 €", "Paquete"],
    ["tarot-field-reading-2h", "Tarot y Lectura de Campo · 2 horas", "Lectura ampliada para preguntas más profundas y el campo energético.", "2 horas", "195,99 €", "Ampliada"],
    ["depression-support-3-months", "Tratamiento para Depresión · 3 meses", "Acompañamiento energético continuo durante tres meses.", "3 meses continuos", "690 €", "Continuo"],
    ["migraine-support", "Tratamiento para Migraña Crónica + Consulta", "Apoyo energético con consulta para casos de migraña crónica.", "30 días", "267,99 €", "Apoyo"],
    ["migraine-support-3-months", "Tratamiento para Migraña Crónica · 3 meses", "Acompañamiento energético continuo para la migraña crónica.", "3 meses continuos", "690 €", "Continuo"],
    ["terminal-transition-support", "Apoyo en Fase Terminal y Transición + Consulta", "Acogida energética en procesos delicados de transición.", "Consulta + apoyo", "150,99 €", "Transición"],
    ["guided-healing-movement", "Movimiento de Cura Guiada con el Equipo Seriana", "Sesión guiada de sanación energética con preparación y formulario obligatorio.", "1 hora", "114,99 €", "Cura guiada"],
    ["mental-relief", "Alivio Mental Inmediato y Confusión Mental", "Sesión para claridad, ligereza mental y organización energética.", "1 hora", "105,99 €", "Claridad"],
    ["trauma-intensive-3", "3 Sesiones Intensivas: Traumas, Bloqueos y Liberaciones", "Paquete de tres sesiones intensivas de dos horas.", "3 sesiones · 2 horas cada una", "555,99 €", "Paquete"],
    ["trauma-intensive-6", "6 Sesiones Intensivas: Traumas, Bloqueos y Liberaciones", "Plan completo de seis sesiones intensivas de dos horas.", "6 sesiones · 2 horas cada una", "996,99 €", "Acompañamiento"],
  ],
  nl: [
    ["environment-harmonization-3-homes", "Harmonisatie van Ruimtes · 3 Woningen", "Pakket voor maximaal drie woningen of ruimtes die balans nodig hebben.", "Tot 3 woningen", "294 €", "Pakket"],
    ["tarot-field-reading-2h", "Tarot en Veldlezing · 2 uur", "Uitgebreide lezing voor diepere vragen en het energetische veld.", "2 uur", "195,99 €", "Uitgebreid"],
    ["depression-support-3-months", "Behandeling bij Depressie · 3 maanden", "Doorlopende energetische ondersteuning gedurende drie maanden.", "3 aaneengesloten maanden", "690 €", "Doorlopend"],
    ["migraine-support", "Ondersteuning bij Chronische Migraine + Consult", "Energetische ondersteuning met consult bij chronische migraine.", "30 dagen", "267,99 €", "Ondersteuning"],
    ["migraine-support-3-months", "Ondersteuning bij Chronische Migraine · 3 maanden", "Doorlopende energetische ondersteuning bij chronische migraine.", "3 aaneengesloten maanden", "690 €", "Doorlopend"],
    ["terminal-transition-support", "Ondersteuning in de Terminale Fase en Overgang + Consult", "Energetische zorg tijdens een gevoelig overgangsproces.", "Consult + ondersteuning", "150,99 €", "Overgang"],
    ["guided-healing-movement", "Begeleide Helingsbeweging met Team Seriana", "Begeleide energetische helingssessie met voorbereiding en verplicht formulier.", "1 uur", "114,99 €", "Begeleide heling"],
    ["mental-relief", "Directe Mentale Verlichting en Mentale Verwarring", "Sessie voor helderheid, mentale lichtheid en energetische ordening.", "1 uur", "105,99 €", "Helderheid"],
    ["trauma-intensive-3", "3 Intensieve Sessies: Trauma, Blokkades en Bevrijding", "Pakket van drie intensieve sessies van twee uur.", "3 sessies · elk 2 uur", "555,99 €", "Pakket"],
    ["trauma-intensive-6", "6 Intensieve Sessies: Trauma, Blokkades en Bevrijding", "Volledig traject van zes intensieve sessies van twee uur.", "6 sessies · elk 2 uur", "996,99 €", "Begeleiding"],
  ],
};

for (const locale of locales) {
  const target = locale === "pt" ? ptServices : locale === "en" ? enServices : locale === "es" ? esServices : nlServices;
  target.push(...additionalServiceCopies[locale].map(([productId, title, text, duration, price, badge]) => ({
    badge,
    duration,
    price,
    productId,
    text,
    title,
  })));
}

export function getServiceTranslation(locale: Locale, productId: string) {
  const services = locale === "pt" ? ptServices : locale === "en" ? enServices : locale === "es" ? esServices : nlServices;
  return services.find((service) => service.productId === productId);
}

const content = {
  pt: {
    metaTitle: "Terapias energéticas e orientação espiritual",
    metaDescription:
      "Sessões online de cuidado energético, orientação espiritual, cursos e desenvolvimento pessoal com Dani Therapies.",
    nav: {
      about: "Quem Somos",
      services: "Sessões",
      courses: "Cursos",
      blog: "Blog",
      contact: "Contato",
      book: "Agendar consulta",
    },
    hero: {
      eyebrow: "Cuidado energético e espiritual",
      title: "Tratamentos Terapêuticos Espirituais e Energéticos e Cursos Online",
      description:
        "Oferecemos serviços online de tratamentos terapêuticos, energéticos e espirituais personalizados, que atuam em múltiplos níveis do Ser.",
      primary: "Agendar primeira consulta",
      secondary: "Conhecer as sessões",
      note: "Atendimento online · Zoom",
    },
    firstVisit: {
      eyebrow: "O primeiro passo",
      title: "Primeira Consulta indispensável para Novos Clientes",
      body: "A primeira consulta é um passo essencial para iniciar o trabalho connosco. Durante este encontro inicial, são recolhidas as informações necessárias para avaliar a sua situação e estabelecer um plano personalizado. A consulta tem a duração de 1 hora e é realizada online, através do Zoom. Durante esse tempo, abordaremos as suas dúvidas, alinharemos expectativas e traçaremos o melhor caminho para alcançar os seus objetivos.",
      imageAlt: "Escultura espiritual branca com dragão entre as nuvens",
      duration: "60 minutos",
      format: "Online, via Zoom",
      action: "Reservar minha consulta",
    },
    about: {
      imageAlt: "Dani Matta, curadora noética espiritual",
      imageCaption: "Não prometo milagres. Ofereço qualidade de vida.",
      title: "Oi! Eu sou a Dani",
      body: "Sou Curadora Noética Espiritual e Educadora do Despertar da Consciência, atuando no trabalho terapêutico, espiritual e energético. A minha missão é conduzir pessoas de volta à sua essência, restaurando a sua energia vital, alinhando os corpos sutis e reconectando cada Ser à sua verdade mais profunda.",
      detailsLabel: "Conhecer a minha trajetória",
      stats: [
        { title: "Acolhimento", text: "Visão ampla, em alta frequência." },
        { title: "Restauração", text: "Restauração vibracional. Quando precisas de voltar à tua base." },
        { title: "Clareza", text: "Que mudanças sentirias em ti após uma Restauração energética?" },
      ],
    },
    promptsTitle: "Sente qual delas te chama agora",
    promptsIntro:
      "Cada processo começa com uma pergunta sincera.",
    promptTones: ["Restauração", "Clareza", "Vínculo", "Libertação", "Orientação", "Equilíbrio"],
    prompts: [
      "A restauração vibracional é tudo! O inimigo não dorme; mantém-te alerta!",
      "Que mudanças sentirias em ti após uma Restauração Energética?",
      "Se o teu querido pet pudesse deixar-te uma mensagem, qual seria?",
      "Libertar um ente querido que já partiu é um ato de amor.",
      "E se pudesses receber uma mensagem direta do teu Guia Espiritual?",
      "A restauração vibracional é a base de tudo!",
    ],
    services: {
      eyebrow: "Sessões e valores",
      title: "Escolha o cuidado que faz sentido agora",
      intro:
        "Consulte a duração e o valor de cada sessão e escolha o cuidado mais adequado para o seu momento.",
      action: "Reservar / pagar",
      detailsLabel: "Ver detalhes",
      items: ptServices,
    },
    servicesPreview: {
      title: "Uma prévia das sessões",
      intro:
        "Conheça alguns dos caminhos disponíveis para o seu cuidado energético e espiritual.",
      allLabel: "Ver todas as sessões",
    },
    course: {
      eyebrow: "Curso online",
      title: "Percepção Sensorial | Aulas em português",
      intro:
        "Curso de desenvolvimento da percepção sensorial por meio do Movimento Guiado de Energia, promovendo o despertar gradual da sensibilidade natural e da leitura sensorial de forma segura e consciente.",
      price: "285 €",
      duration: "6 semanas · início: 15/08/2026 · horário: 21h30 (horário de Amesterdão)",
      cta: "Quero inscrever-me",
      formTitle: "Inscrição no curso",
      name: "Nome",
      age: "Idade",
      email: "E-mail",
      submit: "Continuar inscrição",
      paymentNote:
        "Após preencher os seus dados, poderá continuar para o pagamento seguro.",
      fallback:
        "Se precisar de ajuda com a inscrição, entre em contacto com a Dani pelo WhatsApp.",
    },
    coursePreview: {
      allLabel: "Ver cursos",
      detailsLabel: "Conhecer o curso",
    },
    process: {
      eyebrow: "Como funciona",
      title: "Menos fricção, mais clareza",
      steps: [
        ["01", "Escolha a sessão ou curso", "Consulte a duração, o valor e os detalhes para encontrar o caminho mais adequado."],
        ["02", "Preencha só o necessário", "Curso: nome, idade e e-mail. Atendimento: conversa direta para confirmar o melhor caminho."],
        ["03", "Pague com segurança", "Conclua o pagamento online de forma simples e segura."],
      ],
    },
    quote:
      "Cuidar da energia também é criar espaço para novas escolhas, novos sentidos e uma vida mais consciente.",
    blogPreview: {
      title: "Blog da Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Ver blog completo",
    },
    contact: {
      eyebrow: "Vamos conversar",
      title: "Qual transformação procura neste momento?",
      body: "Envie uma mensagem breve. Ela será encaminhada diretamente ao WhatsApp da Dani Therapies.",
      name: "Seu nome",
      email: "Seu e-mail",
      message: "Como podemos ajudar?",
      submit: "Enviar pelo WhatsApp",
      privacy: "Os seus dados não serão armazenados neste primeiro contacto.",
    },
    footer: {
      text: "Cuidado energético e espiritual com presença, respeito e acolhimento.",
      rights: "Todos os direitos reservados.",
      disclaimer:
        "As sessões oferecidas não substituem acompanhamento médico, psicológico ou emergencial.",
      legal: {
        cookies: "Política de Cookies",
        terms: "Termos e Condições",
        privacy: "Política de Privacidade",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Falar pelo WhatsApp",
  },
  en: {
    metaTitle: "Energy therapies and spiritual guidance",
    metaDescription:
      "Online sessions for energetic care, spiritual guidance, courses and personal development with Dani Therapies.",
    nav: { about: "About", services: "Sessions", courses: "Courses", blog: "Journal", contact: "Contact", book: "Book a session" },
    hero: {
      eyebrow: "Energetic and spiritual care",
      title: "A safe space to restore your energy and listen to your essence.",
      description: "Online sessions guided with presence, sensitivity and respect for your moment.",
      primary: "Book your first session",
      secondary: "Explore the sessions",
      note: "Online · Zoom",
    },
    firstVisit: {
      eyebrow: "The first step",
      title: "First consultation, essential for new clients",
      body: "The first consultation is an essential step to begin our work together. During this initial meeting, we gather the information needed to understand your situation and establish a personalised plan. The consultation lasts 1 hour and takes place online via Zoom. We discuss your questions, align expectations and outline the best path towards your goals.",
      imageAlt: "White spiritual sculpture with a dragon among the clouds",
      duration: "60 minutes",
      format: "Online via Zoom",
      action: "Book my consultation",
    },
    about: {
      imageAlt: "Dani Therapies during an energetic care session",
      imageCaption: "Healing, guidance and presence for energetic and spiritual processes.",
      title: "Sensitive work with a clear structure.",
      body: "I am a Spiritual Noetic Healer and Consciousness Awakening Educator, working with therapeutic, spiritual and energetic care. My mission is to guide people back to their essence, restoring vital energy, aligning the subtle bodies and reconnecting each being with their deepest truth.",
      detailsLabel: "Read my full story",
      stats: [
        { title: "Online", text: "Sessions by video call" },
        { title: "4 languages", text: "Portuguese, English, Spanish and Dutch" },
        { title: "Care", text: "Sensitive listening and spiritual guidance" },
      ],
    },
    promptsTitle: "Perhaps one of these questions speaks to you",
    promptsIntro: "Every process begins with an honest question. Discover which path resonates with your present moment.",
    promptTones: ["Restoration", "Clarity", "Bond", "Release", "Guidance", "Balance"],
    prompts: [
      "Vibrational restoration is everything! The enemy never sleeps; stay alert!",
      "What changes would you feel within yourself after an Energetic Restoration?",
      "If your beloved pet could leave you a message, what would it be?",
      "Releasing a loved one who has passed is an act of love.",
      "What if you could receive a direct message from your Spiritual Guide?",
      "Vibrational restoration is the foundation of everything!",
    ],
    services: {
      eyebrow: "Sessions and prices",
      title: "Choose the care that fits your moment",
      intro: "Review the duration and price of each session and choose the care that best suits your present moment.",
      action: "Book / pay",
      detailsLabel: "View details",
      items: enServices,
    },
    servicesPreview: {
      title: "A preview of the sessions",
      intro: "Discover some of the available pathways for your energetic and spiritual care.",
      allLabel: "View all sessions",
    },
    course: {
      eyebrow: "Online course",
      title: "Sensory Perception | Lessons in English",
      intro: "There are several ways to practise sensory reading. One is to activate the sensory body through perception exercises. When we activate the body's cells, our natural sensitivity awakens again.",
      price: "€384,00",
      duration: "6 weeks · starts: 21/11/2026 · time: 21:30 (Amsterdam time)",
      cta: "I want to enrol",
      formTitle: "Course enrolment",
      name: "Name",
      age: "Age",
      email: "Email",
      submit: "Continue enrolment",
      paymentNote: "After completing your details, you can continue to secure payment.",
      fallback: "If you need help with enrolment, contact Dani via WhatsApp.",
    },
    coursePreview: {
      allLabel: "View courses",
      detailsLabel: "Explore the course",
    },
    process: {
      eyebrow: "How it works",
      title: "Less friction, more clarity",
      steps: [
        ["01", "Choose a session or course", "Review the duration, price and details to find the most suitable path."],
        ["02", "Share only what is needed", "Course: name, age and email. Session: direct conversation to confirm the best path."],
        ["03", "Pay securely", "Complete your online payment simply and securely."],
      ],
    },
    quote: "Caring for your energy also means creating space for new choices, new meaning and a more conscious life.",
    blogPreview: {
      title: "Dani Therapies Journal",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "View full journal",
    },
    contact: {
      eyebrow: "Let’s talk",
      title: "What transformation are you seeking right now?",
      body: "Send a short message. It will be forwarded directly to Dani Therapies on WhatsApp.",
      name: "Your name",
      email: "Your email",
      message: "How can we help?",
      submit: "Send via WhatsApp",
      privacy: "Your details will not be stored during this first contact.",
    },
    footer: {
      text: "Energetic and spiritual care with presence, respect and warmth.",
      rights: "All rights reserved.",
      disclaimer: "The sessions offered do not replace medical, psychological or emergency care.",
      legal: {
        cookies: "Cookie Policy",
        terms: "Terms and Conditions",
        privacy: "Privacy Policy",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Chat on WhatsApp",
  },
  es: {
    metaTitle: "Terapias energéticas y orientación espiritual",
    metaDescription: "Sesiones online de cuidado energético, orientación espiritual, cursos y desarrollo personal con Dani Therapies.",
    nav: { about: "Sobre mí", services: "Sesiones", courses: "Cursos", blog: "Reflexiones", contact: "Contacto", book: "Reservar consulta" },
    hero: {
      eyebrow: "Cuidado energético y espiritual",
      title: "Un espacio seguro para restaurar tu energía y escuchar tu esencia.",
      description: "Sesiones online guiadas con presencia, sensibilidad y respeto por tu momento.",
      primary: "Reservar primera consulta",
      secondary: "Conocer las sesiones",
      note: "Online · Zoom",
    },
    firstVisit: {
      eyebrow: "El primer paso",
      title: "Primera consulta, indispensable para nuevos clientes",
      body: "La primera consulta es un paso esencial para comenzar nuestro trabajo. Durante este encuentro inicial, recopilamos la información necesaria para comprender tu situación y establecer un plan personalizado. La consulta dura 1 hora y se realiza online por Zoom. Abordaremos tus dudas, alinearemos expectativas y trazaremos el mejor camino para alcanzar tus objetivos.",
      imageAlt: "Escultura espiritual blanca con un dragón entre las nubes",
      duration: "60 minutos",
      format: "Online por Zoom",
      action: "Reservar mi consulta",
    },
    about: {
      imageAlt: "Dani Therapies durante una sesión de cuidado energético",
      imageCaption: "Cura, guía y presencia para procesos energéticos y espirituales.",
      title: "Un trabajo sensible, con una estructura clara.",
      body: "Soy Sanadora Noética Espiritual y Educadora del Despertar de la Conciencia, y trabajo con el cuidado terapéutico, espiritual y energético. Mi misión es guiar a las personas de regreso a su esencia, restaurando su energía vital, alineando los cuerpos sutiles y reconectando cada Ser con su verdad más profunda.",
      detailsLabel: "Conocer mi trayectoria",
      stats: [
        { title: "Online", text: "Sesiones por videollamada" },
        { title: "4 idiomas", text: "Portugués, inglés, español y neerlandés" },
        { title: "Acogida", text: "Escucha sensible y orientación espiritual" },
      ],
    },
    promptsTitle: "Quizás alguna de estas preguntas hable contigo",
    promptsIntro: "Cada proceso comienza con una pregunta sincera. Descubre qué camino se acerca a tu momento actual.",
    promptTones: ["Restauración", "Claridad", "Vínculo", "Liberación", "Orientación", "Equilibrio"],
    prompts: [
      "¡La restauración vibracional lo es todo! El enemigo no duerme; ¡mantente alerta!",
      "¿Qué cambios sentirías en ti después de una Restauración Energética?",
      "Si tu querida mascota pudiera dejarte un mensaje, ¿cuál sería?",
      "Liberar a un ser querido que ya partió es un acto de amor.",
      "¿Y si pudieras recibir un mensaje directo de tu Guía Espiritual?",
      "¡La restauración vibracional es la base de todo!",
    ],
    services: {
      eyebrow: "Sesiones y valores",
      title: "Elige el cuidado que encaja con tu momento",
      intro: "Consulta la duración y el valor de cada sesión y elige el cuidado más adecuado para tu momento actual.",
      action: "Reservar / pagar",
      detailsLabel: "Ver detalles",
      items: esServices,
    },
    servicesPreview: {
      title: "Una vista previa de las sesiones",
      intro: "Descubre algunos de los caminos disponibles para tu cuidado energético y espiritual.",
      allLabel: "Ver todas las sesiones",
    },
    course: {
      eyebrow: "Curso online",
      title: "Percepción Sensorial",
      intro: "Existen varias formas de realizar la lectura sensorial. Una de ellas es activar el cuerpo sensorial mediante ejercicios de percepción. Al activar las células del cuerpo, la sensibilidad natural vuelve a despertar.",
      price: "285 €",
      duration: "6 semanas · inicio: 15/08/2026",
      cta: "Quiero inscribirme",
      formTitle: "Inscripción en el curso",
      name: "Nombre",
      age: "Edad",
      email: "Email",
      submit: "Continuar inscripción",
      paymentNote: "Después de completar tus datos, podrás continuar al pago seguro.",
      fallback: "Si necesitas ayuda con la inscripción, contacta con Dani por WhatsApp.",
    },
    coursePreview: {
      allLabel: "Ver cursos",
      detailsLabel: "Conocer el curso",
    },
    process: {
      eyebrow: "Cómo funciona",
      title: "Menos fricción, más claridad",
      steps: [
        ["01", "Elige sesión o curso", "Consulta la duración, el valor y los detalles para encontrar el camino más adecuado."],
        ["02", "Rellena solo lo necesario", "Curso: nombre, edad y email. Atención: conversación directa para confirmar el mejor camino."],
        ["03", "Paga con seguridad", "Completa el pago online de forma sencilla y segura."],
      ],
    },
    quote: "Cuidar la energía también es crear espacio para nuevas elecciones, nuevos sentidos y una vida más consciente.",
    blogPreview: {
      title: "Reflexiones de Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Ver blog completo",
    },
    contact: {
      eyebrow: "Hablemos",
      title: "¿Qué transformación buscas en este momento?",
      body: "Envía un mensaje breve. Será dirigido directamente al WhatsApp de Dani Therapies.",
      name: "Tu nombre",
      email: "Tu email",
      message: "¿Cómo podemos ayudarte?",
      submit: "Enviar por WhatsApp",
      privacy: "Tus datos no serán almacenados en este primer contacto.",
    },
    footer: {
      text: "Cuidado energético y espiritual con presencia, respeto y acogida.",
      rights: "Todos los derechos reservados.",
      disclaimer: "Las sesiones ofrecidas no sustituyen la atención médica, psicológica o de emergencia.",
      legal: {
        cookies: "Política de Cookies",
        terms: "Términos y Condiciones",
        privacy: "Política de Privacidad",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Hablar por WhatsApp",
  },
  nl: {
    metaTitle: "Energetische therapie en spirituele begeleiding",
    metaDescription: "Online sessies voor energetische zorg, spirituele begeleiding, cursussen en persoonlijke ontwikkeling bij Dani Therapies.",
    nav: { about: "Over", services: "Sessies", courses: "Cursussen", blog: "Inspiratie", contact: "Contact", book: "Sessie boeken" },
    hero: {
      eyebrow: "Energetische en spirituele zorg",
      title: "Een veilige ruimte om je energie te herstellen en naar je essentie te luisteren.",
      description: "Online sessies met aandacht, gevoeligheid en respect voor jouw moment.",
      primary: "Eerste consult boeken",
      secondary: "Bekijk de sessies",
      note: "Online · Zoom",
    },
    firstVisit: {
      eyebrow: "De eerste stap",
      title: "Eerste consult, essentieel voor nieuwe cliënten",
      body: "Het eerste consult is een essentiële stap om onze samenwerking te beginnen. Tijdens deze kennismaking verzamelen we de informatie die nodig is om jouw situatie te begrijpen en een persoonlijk plan op te stellen. Het consult duurt 1 uur en vindt online plaats via Zoom. We bespreken je vragen, stemmen verwachtingen af en bepalen samen de beste weg naar je doelen.",
      imageAlt: "Wit spiritueel beeld met een draak tussen de wolken",
      duration: "60 minuten",
      format: "Online via Zoom",
      action: "Mijn consult boeken",
    },
    about: {
      imageAlt: "Dani Therapies tijdens een energetische sessie",
      imageCaption: "Heling, begeleiding en aanwezigheid voor energetische en spirituele processen.",
      title: "Gevoelig werk met een duidelijke structuur.",
      body: "Ik ben Spiritueel Noëtisch Healer en begeleider bij het Ontwaken van Bewustzijn, met therapeutische, spirituele en energetische zorg. Mijn missie is mensen terug te begeleiden naar hun essentie, hun levensenergie te herstellen, de subtiele lichamen op één lijn te brengen en ieder mens opnieuw te verbinden met zijn diepste waarheid.",
      detailsLabel: "Lees mijn volledige verhaal",
      stats: [
        { title: "Online", text: "Sessies via videogesprek" },
        { title: "4 talen", text: "Portugees, Engels, Spaans en Nederlands" },
        { title: "Aandacht", text: "Gevoelig luisteren en spirituele begeleiding" },
      ],
    },
    promptsTitle: "Misschien spreekt een van deze vragen je aan",
    promptsIntro: "Elk proces begint met een oprechte vraag. Ontdek welk pad past bij jouw huidige moment.",
    promptTones: ["Herstel", "Helderheid", "Verbinding", "Loslaten", "Begeleiding", "Balans"],
    prompts: [
      "Vibrationeel herstel is alles! De vijand slaapt niet; blijf alert!",
      "Welke veranderingen zou je in jezelf voelen na een Energetisch Herstel?",
      "Als je geliefde huisdier je een boodschap kon nalaten, welke zou dat zijn?",
      "Een dierbare die is heengegaan loslaten is een daad van liefde.",
      "Wat als je een rechtstreekse boodschap van je Spirituele Gids kon ontvangen?",
      "Vibrationeel herstel is de basis van alles!",
    ],
    services: {
      eyebrow: "Sessies en prijzen",
      title: "Kies de zorg die nu bij je past",
      intro: "Bekijk de duur en prijs van elke sessie en kies de zorg die het beste bij jouw huidige moment past.",
      action: "Boeken / betalen",
      detailsLabel: "Bekijk details",
      items: nlServices,
    },
    servicesPreview: {
      title: "Een preview van de sessies",
      intro: "Ontdek enkele beschikbare paden voor jouw energetische en spirituele welzijn.",
      allLabel: "Bekijk alle sessies",
    },
    course: {
      eyebrow: "Online cursus",
      title: "Zintuiglijke Waarneming",
      intro: "Er zijn verschillende manieren om zintuiglijk waar te nemen. Een daarvan is het activeren van het zintuiglijke lichaam met waarnemingsoefeningen. Wanneer we de lichaamscellen activeren, ontwaakt de natuurlijke gevoeligheid opnieuw.",
      price: "285 €",
      duration: "6 weken · start: 15/08/2026",
      cta: "Ik wil me inschrijven",
      formTitle: "Cursusinschrijving",
      name: "Naam",
      age: "Leeftijd",
      email: "E-mail",
      submit: "Inschrijving doorgaan",
      paymentNote: "Na het invullen van je gegevens kun je doorgaan naar de beveiligde betaling.",
      fallback: "Neem via WhatsApp contact op met Dani als je hulp nodig hebt bij de inschrijving.",
    },
    coursePreview: {
      allLabel: "Bekijk cursussen",
      detailsLabel: "Ontdek de cursus",
    },
    process: {
      eyebrow: "Hoe het werkt",
      title: "Minder frictie, meer duidelijkheid",
      steps: [
        ["01", "Kies een sessie of cursus", "Bekijk de duur, prijs en details om het meest geschikte pad te vinden."],
        ["02", "Deel alleen wat nodig is", "Cursus: naam, leeftijd en e-mail. Sessie: direct gesprek om de beste route te bevestigen."],
        ["03", "Betaal veilig", "Rond de online betaling eenvoudig en veilig af."],
      ],
    },
    quote: "Voor je energie zorgen betekent ook ruimte maken voor nieuwe keuzes, nieuwe betekenis en een bewuster leven.",
    blogPreview: {
      title: "Inspiratie van Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Bekijk alle inspiratie",
    },
    contact: {
      eyebrow: "Laten we praten",
      title: "Welke verandering zoek je op dit moment?",
      body: "Stuur een kort bericht. Het wordt rechtstreeks doorgestuurd naar Dani Therapies via WhatsApp.",
      name: "Je naam",
      email: "Je e-mail",
      message: "Hoe kunnen we helpen?",
      submit: "Verstuur via WhatsApp",
      privacy: "Je gegevens worden tijdens dit eerste contact niet opgeslagen.",
    },
    footer: {
      text: "Energetische en spirituele zorg met aandacht, respect en warmte.",
      rights: "Alle rechten voorbehouden.",
      disclaimer: "De aangeboden sessies vervangen geen medische, psychologische of spoedeisende zorg.",
      legal: {
        cookies: "Cookiebeleid",
        terms: "Algemene voorwaarden",
        privacy: "Privacybeleid",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Praat via WhatsApp",
  },
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}
