import type { ProductId } from "./catalog";

export const locales = ["pt", "en", "es", "nl"] as const;
export type Locale = (typeof locales)[number];

export const localeOptions: Record<Locale, { flag: string; short: string; label: string }> = {
  pt: { flag: "/flag-pt.svg", short: "PT", label: "Português" },
  en: { flag: "/flag-en.svg", short: "EN", label: "English" },
  es: { flag: "/flag-es.svg", short: "ES", label: "Español" },
  nl: { flag: "/flag-nl.svg", short: "NL", label: "Nederlands" },
};

type ServiceCopy = {
  productId: Exclude<ProductId, "online-course">;
  title: string;
  text: string;
  duration: string;
  price: string;
  badge: string;
};

const ptServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Primeira Consulta Online",
    text: "Encontro inicial para compreender a sua situação e definir um plano personalizado.",
    duration: "1 hora · online",
    price: "69 €",
    badge: "Novos clientes",
  },
  {
    productId: "energy-cleansing",
    title: "Limpeza Energética & Espiritual",
    text: "Restauração vibracional, limpeza de cargas e harmonização da aura e dos corpos sutis.",
    duration: "Sessão à distância",
    price: "114,99 €",
    badge: "Restauro",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Limpeza + 1ª Consulta",
    text: "Opção indicada para quem ainda precisa da consulta inicial antes da limpeza energética.",
    duration: "Consulta + tratamento",
    price: "150,99 €",
    badge: "Pacote inicial",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarô & Leitura de Campo",
    text: "Leitura para questões específicas, com orientação espiritual por chamada online.",
    duration: "1 hora",
    price: "105,99 €",
    badge: "Orientação",
  },
  {
    productId: "chakra-restoration",
    title: "Restauração Integral dos Chakras",
    text: "Cuidado focado no equilíbrio energético, conexão corporal e estabilidade interior.",
    duration: "À distância",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas e Bloqueios",
    text: "Sessão intensiva para padrões profundos, bloqueios emocionais e desorientação energética.",
    duration: "Sessão intensiva",
    price: "204,99 €",
    badge: "Intensivo",
  },
  {
    productId: "depression-support",
    title: "Tratamento para Depressão",
    text: "Apoio energético intensivo à distância, com primeira consulta e acompanhamento estruturado.",
    duration: "15 dias",
    price: "267,99 €",
    badge: "Apoio",
  },
  {
    productId: "environment-harmonization",
    title: "Harmonização de Ambientes",
    text: "Limpeza e equilíbrio energético para residências ou espaços que estejam carregados.",
    duration: "Até 3 residências",
    price: "294 €",
    badge: "Ambientes",
  },
];

const enServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "First Online Consultation",
    text: "Initial meeting to understand your situation and define a personalised plan.",
    duration: "1 hour · online",
    price: "69 €",
    badge: "New clients",
  },
  {
    productId: "energy-cleansing",
    title: "Energetic & Spiritual Cleansing",
    text: "Vibrational restoration, cleansing of heavy energy and harmonisation of the aura and subtle bodies.",
    duration: "Remote session",
    price: "114.99 €",
    badge: "Restore",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Cleansing + First Consultation",
    text: "Recommended for those who still need the initial consultation before energetic cleansing.",
    duration: "Consultation + treatment",
    price: "150.99 €",
    badge: "Starter pack",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot & Field Reading",
    text: "Reading for specific questions with spiritual guidance through an online call.",
    duration: "1 hour",
    price: "105.99 €",
    badge: "Guidance",
  },
  {
    productId: "chakra-restoration",
    title: "Integral Chakra Restoration",
    text: "Care focused on energetic balance, body connection and inner stability.",
    duration: "Remote",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas and Blockages",
    text: "Intensive session for deep patterns, emotional blocks and energetic disorientation.",
    duration: "Intensive session",
    price: "204.99 €",
    badge: "Intensive",
  },
  {
    productId: "depression-support",
    title: "Depression Support Treatment",
    text: "Intensive remote energetic support with first consultation and structured follow-up.",
    duration: "15 days",
    price: "267.99 €",
    badge: "Support",
  },
  {
    productId: "environment-harmonization",
    title: "Environment Harmonisation",
    text: "Energetic cleansing and balancing for homes or spaces that feel heavy.",
    duration: "Up to 3 homes",
    price: "294 €",
    badge: "Spaces",
  },
];

const esServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Primera Consulta Online",
    text: "Encuentro inicial para comprender tu situación y definir un plan personalizado.",
    duration: "1 hora · online",
    price: "69 €",
    badge: "Nuevos clientes",
  },
  {
    productId: "energy-cleansing",
    title: "Limpieza Energética y Espiritual",
    text: "Restauración vibracional, limpieza de cargas y armonización del aura y cuerpos sutiles.",
    duration: "Sesión a distancia",
    price: "114,99 €",
    badge: "Restauración",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Limpieza + Primera Consulta",
    text: "Opción indicada para quien aún necesita la consulta inicial antes de la limpieza energética.",
    duration: "Consulta + tratamiento",
    price: "150,99 €",
    badge: "Pack inicial",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot y Lectura de Campo",
    text: "Lectura para preguntas específicas con orientación espiritual por llamada online.",
    duration: "1 hora",
    price: "105,99 €",
    badge: "Orientación",
  },
  {
    productId: "chakra-restoration",
    title: "Restauración Integral de Chakras",
    text: "Cuidado enfocado en equilibrio energético, conexión corporal y estabilidad interior.",
    duration: "A distancia",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Traumas y Bloqueos",
    text: "Sesión intensiva para patrones profundos, bloqueos emocionales y desorientación energética.",
    duration: "Sesión intensiva",
    price: "204,99 €",
    badge: "Intensivo",
  },
  {
    productId: "depression-support",
    title: "Tratamiento para Depresión",
    text: "Apoyo energético intensivo a distancia, con primera consulta y seguimiento estructurado.",
    duration: "15 días",
    price: "267,99 €",
    badge: "Apoyo",
  },
  {
    productId: "environment-harmonization",
    title: "Armonización de Ambientes",
    text: "Limpieza y equilibrio energético para residencias o espacios que se sienten cargados.",
    duration: "Hasta 3 residencias",
    price: "294 €",
    badge: "Ambientes",
  },
];

const nlServices: ServiceCopy[] = [
  {
    productId: "first-consultation",
    title: "Eerste Online Consult",
    text: "Eerste gesprek om jouw situatie te begrijpen en een persoonlijk plan te bepalen.",
    duration: "1 uur · online",
    price: "69 €",
    badge: "Nieuwe cliënten",
  },
  {
    productId: "energy-cleansing",
    title: "Energetische & Spirituele Reiniging",
    text: "Vibrationeel herstel, reiniging van zware energie en harmonisatie van aura en subtiele lichamen.",
    duration: "Sessie op afstand",
    price: "114,99 €",
    badge: "Herstel",
  },
  {
    productId: "energy-cleansing-initial",
    title: "Reiniging + Eerste Consult",
    text: "Aangeraden voor wie eerst een kennismakingsconsult nodig heeft voor de energetische reiniging.",
    duration: "Consult + behandeling",
    price: "150,99 €",
    badge: "Startpakket",
  },
  {
    productId: "tarot-field-reading",
    title: "Tarot & Veldlezing",
    text: "Lezing voor specifieke vragen met spirituele begeleiding via online gesprek.",
    duration: "1 uur",
    price: "105,99 €",
    badge: "Begeleiding",
  },
  {
    productId: "chakra-restoration",
    title: "Integrale Chakra Herstelling",
    text: "Zorg gericht op energetisch evenwicht, lichaamsverbinding en innerlijke stabiliteit.",
    duration: "Op afstand",
    price: "120 €",
    badge: "Chakras",
  },
  {
    productId: "trauma-intensive",
    title: "Trauma's en Blokkades",
    text: "Intensieve sessie voor diepe patronen, emotionele blokkades en energetische desoriëntatie.",
    duration: "Intensieve sessie",
    price: "204,99 €",
    badge: "Intensief",
  },
  {
    productId: "depression-support",
    title: "Behandeling bij Depressie",
    text: "Intensieve energetische ondersteuning op afstand, met eerste consult en gestructureerde opvolging.",
    duration: "15 dagen",
    price: "267,99 €",
    badge: "Steun",
  },
  {
    productId: "environment-harmonization",
    title: "Harmonisatie van Ruimtes",
    text: "Energetische reiniging en balans voor woningen of ruimtes die zwaar aanvoelen.",
    duration: "Tot 3 woningen",
    price: "294 €",
    badge: "Ruimtes",
  },
];

const content = {
  pt: {
    metaTitle: "Terapias energéticas e orientação espiritual",
    metaDescription:
      "Sessões online de cuidado energético, orientação espiritual, cursos e desenvolvimento pessoal com Dani Therapies.",
    nav: {
      about: "Quem Somos",
      services: "Sessões",
      courses: "Cursos",
      blog: "Blog",
      contact: "Contato",
      book: "Agendar consulta",
    },
    hero: {
      eyebrow: "Cuidado energético e espiritual",
      title: "Tratamentos Terapêuticos Espirituais e Energéticos e Cursos Online",
      description:
        "Oferecemos serviços online de tratamentos terapêuticos, energéticos e espirituais personalizados, que atuam em múltiplos níveis do Ser.",
      primary: "Agendar primeira consulta",
      secondary: "Conhecer as sessões",
      note: "Atendimento online · Zoom · Europa",
    },
    firstVisit: {
      eyebrow: "O primeiro passo",
      title: "Primeira Consulta indispensável para Novos Clientes",
      body: "A primeira consulta é um passo essencial para iniciar o trabalho connosco. Durante este encontro inicial, são recolhidas as informações necessárias para avaliar a sua situação e estabelecer um plano personalizado. A consulta tem a duração de 1 hora e é realizada online, através do Zoom. Durante esse tempo, abordaremos as suas dúvidas, alinharemos expectativas e traçaremos o melhor caminho para alcançar os seus objetivos.",
      imageAlt: "Escultura espiritual branca com dragão entre as nuvens",
      duration: "60 minutos",
      format: "Online, via Zoom",
      action: "Reservar minha consulta",
    },
    about: {
      imageAlt: "Dani Matta, curadora noética espiritual",
      imageCaption: "Não prometo milagres. Mas ofereço qualidade de vida.",
      title: "Oi! Eu sou a Dani",
      body: "Sou Curadora Noética Espiritual e Educadora do Despertar da Consciência, atuando no trabalho terapêutico, espiritual e energético. A minha missão é conduzir pessoas de volta à sua essência, restaurando a sua energia vital, alinhando os corpos sutis e reconectando cada Ser à sua verdade mais profunda.",
      stats: [
        { title: "Acolhimento", text: "Visão ampla, em alta frequência." },
        { title: "Restauração", text: "Restauração vibracional. Quando precisas de voltar à tua base." },
        { title: "Clareza", text: "Que mudanças sentirias em ti após uma Restauração energética?" },
      ],
    },
    promptsTitle: "Sente qual delas te chama agora",
    promptsIntro:
      "Cada processo começa com uma pergunta sincera.",
    promptTones: ["Restauração", "Clareza", "Vínculo"],
    prompts: [
      "Restauração vibracional. Quando precisas de voltar à tua base.",
      "Que mudanças sentirias em ti após uma Restauração energética?",
      "Se o teu querido animal pudesse deixar-te uma mensagem, qual seria?",
      "Libertar um ente querido que já partiu é um ato de amor.",
      "E se pudesse receber uma mensagem direta do teu Guia Espiritual?",
    ],
    services: {
      eyebrow: "Sessões e valores",
      title: "Escolha o cuidado que faz sentido agora",
      intro:
        "Valores baseados nas sessões disponíveis no site atual. A confirmação final acontece antes do pagamento, com Stripe preparado para euro.",
      action: "Reservar / pagar",
      items: ptServices,
    },
    servicesPreview: {
      title: "Uma prévia das sessões",
      intro:
        "A home mostra apenas alguns caminhos. A lista completa fica numa página própria, com valores, duração e checkout preparado.",
      allLabel: "Ver todas as sessões",
    },
    course: {
      eyebrow: "Curso online",
      title: "Ativação Sensorial (Classes em português)",
      intro:
        "Curso online para desenvolver a leitura sensorial por meio de exercícios de percepção, meditação, respiração e ativação do corpo sensorial.",
      price: "285 €",
      duration: "6 semanas · início: 15/08/2026",
      cta: "Quero inscrever-me",
      formTitle: "Inscrição no curso",
      name: "Nome",
      age: "Idade",
      email: "E-mail",
      submit: "Continuar inscrição",
      paymentNote:
        "A base do Stripe já está preparada. Quando as chaves e os Price IDs forem adicionados, este formulário envia a pessoa para o checkout.",
      fallback:
        "Se o pagamento ainda não estiver ativo, a inscrição é enviada por WhatsApp para a Dani dar seguimento.",
    },
    coursePreview: {
      allLabel: "Ver cursos",
      note: "Inscrição separada para manter a página principal mais leve.",
    },
    process: {
      eyebrow: "Como funciona",
      title: "Menos fricção, mais clareza",
      steps: [
        ["01", "Escolha a sessão ou curso", "A página mostra duração, valor e o próximo passo sem páginas soltas."],
        ["02", "Preencha só o necessário", "Curso: nome, idade e e-mail. Atendimento: conversa direta para confirmar o melhor caminho."],
        ["03", "Pague com segurança", "Stripe fica pronto para cartões europeus e pagamentos em euro quando a cliente enviar as chaves."],
      ],
    },
    quote:
      "Cuidar da energia também é criar espaço para novas escolhas, novos sentidos e uma vida mais consciente.",
    blogPreview: {
      title: "Blog da Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Ver blog completo",
    },
    contact: {
      eyebrow: "Vamos conversar",
      title: "Qual transformação procura neste momento?",
      body: "Envie uma mensagem breve. Ela será encaminhada diretamente ao WhatsApp da Dani Therapies.",
      name: "Seu nome",
      email: "Seu e-mail",
      message: "Como podemos ajudar?",
      submit: "Enviar pelo WhatsApp",
      privacy: "Os seus dados não serão armazenados neste primeiro contacto.",
    },
    footer: {
      text: "Cuidado energético e espiritual com presença, respeito e acolhimento.",
      rights: "Todos os direitos reservados.",
      disclaimer:
        "As sessões oferecidas não substituem acompanhamento médico, psicológico ou emergencial.",
      legal: {
        cookies: "Política de Cookies",
        terms: "Termos e Condições",
        privacy: "Política de Privacidade",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Falar pelo WhatsApp",
  },
  en: {
    metaTitle: "Energy therapies and spiritual guidance",
    metaDescription:
      "Online sessions for energetic care, spiritual guidance, courses and personal development with Dani Therapies.",
    nav: { about: "About", services: "Sessions", courses: "Courses", blog: "Journal", contact: "Contact", book: "Book a session" },
    hero: {
      eyebrow: "Energetic and spiritual care",
      title: "A safe space to restore your energy and listen to your essence.",
      description: "Online sessions guided with presence, sensitivity and respect for your moment.",
      primary: "Book your first session",
      secondary: "Explore the sessions",
      note: "Online · Zoom · Europe",
    },
    firstVisit: {
      eyebrow: "The first step",
      title: "First consultation, essential for new clients",
      body: "The first consultation is an essential step to begin our work together. During this initial meeting, we gather the information needed to understand your situation and establish a personalised plan. The consultation lasts 1 hour and takes place online via Zoom. We discuss your questions, align expectations and outline the best path towards your goals.",
      imageAlt: "White spiritual sculpture with a dragon among the clouds",
      duration: "60 minutes",
      format: "Online via Zoom",
      action: "Book my consultation",
    },
    about: {
      imageAlt: "Dani Therapies during an energetic care session",
      imageCaption: "Healing, guidance and presence for energetic and spiritual processes.",
      title: "Sensitive work with a clear structure.",
      body: "The main page introduces the essence of the work, the first consultation, selected pathways and contact. Full sessions and courses have their own pages, so the website stays lighter, calmer and easy to navigate on mobile.",
      stats: [
        { title: "Online", text: "Sessions by video call" },
        { title: "4 languages", text: "Portuguese, English, Spanish and Dutch" },
        { title: "Care", text: "Sensitive listening and spiritual guidance" },
      ],
    },
    promptsTitle: "Perhaps one of these questions speaks to you",
    promptsIntro: "Every process begins with an honest question. Discover which path resonates with your present moment.",
    promptTones: ["Restoration", "Clarity", "Bond"],
    prompts: [
      "Vibrational restoration matters. Stay aware and protect your energy.",
      "What would you notice in yourself after an energetic restoration?",
      "If your beloved pet could leave you a message, what would it be?",
      "Releasing a loved one who has passed can be an act of love.",
      "What if you could receive a direct message from your Spiritual Guide?",
    ],
    services: {
      eyebrow: "Sessions and prices",
      title: "Choose the care that fits your moment",
      intro: "Prices are based on the current available sessions. Final confirmation happens before payment, with Stripe prepared for euros.",
      action: "Book / pay",
      items: enServices,
    },
    servicesPreview: {
      title: "A preview of the sessions",
      intro: "The home page shows only a few pathways. The complete list has its own page, with prices, duration and checkout prepared.",
      allLabel: "View all sessions",
    },
    course: {
      eyebrow: "Online course",
      title: "Ativação Sensorial (Classes em português)",
      intro: "Online course to develop sensory reading through perception exercises, meditation, breathing and activation of the sensory body.",
      price: "285 €",
      duration: "6 weeks · starts: 15/08/2026",
      cta: "I want to enrol",
      formTitle: "Course enrolment",
      name: "Name",
      age: "Age",
      email: "Email",
      submit: "Continue enrolment",
      paymentNote: "Stripe is already prepared. Once keys and Price IDs are added, this form sends the person to checkout.",
      fallback: "If payment is not active yet, the enrolment is sent via WhatsApp so Dani can follow up.",
    },
    coursePreview: {
      allLabel: "View courses",
      note: "Separate enrolment keeps the main page lighter.",
    },
    process: {
      eyebrow: "How it works",
      title: "Less friction, more clarity",
      steps: [
        ["01", "Choose a session or course", "The page shows duration, price and the next step without scattered pages."],
        ["02", "Share only what is needed", "Course: name, age and email. Session: direct conversation to confirm the best path."],
        ["03", "Pay securely", "Stripe is ready for European card payments and euro checkout once the client sends the keys."],
      ],
    },
    quote: "Caring for your energy also means creating space for new choices, new meaning and a more conscious life.",
    blogPreview: {
      title: "Dani Therapies Journal",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "View full journal",
    },
    contact: {
      eyebrow: "Let’s talk",
      title: "What transformation are you seeking right now?",
      body: "Send a short message. It will be forwarded directly to Dani Therapies on WhatsApp.",
      name: "Your name",
      email: "Your email",
      message: "How can we help?",
      submit: "Send via WhatsApp",
      privacy: "Your details will not be stored during this first contact.",
    },
    footer: {
      text: "Energetic and spiritual care with presence, respect and warmth.",
      rights: "All rights reserved.",
      disclaimer: "The sessions offered do not replace medical, psychological or emergency care.",
      legal: {
        cookies: "Cookie Policy",
        terms: "Terms and Conditions",
        privacy: "Privacy Policy",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Chat on WhatsApp",
  },
  es: {
    metaTitle: "Terapias energéticas y orientación espiritual",
    metaDescription: "Sesiones online de cuidado energético, orientación espiritual, cursos y desarrollo personal con Dani Therapies.",
    nav: { about: "Sobre mí", services: "Sesiones", courses: "Cursos", blog: "Reflexiones", contact: "Contacto", book: "Reservar consulta" },
    hero: {
      eyebrow: "Cuidado energético y espiritual",
      title: "Un espacio seguro para restaurar tu energía y escuchar tu esencia.",
      description: "Sesiones online guiadas con presencia, sensibilidad y respeto por tu momento.",
      primary: "Reservar primera consulta",
      secondary: "Conocer las sesiones",
      note: "Online · Zoom · Europa",
    },
    firstVisit: {
      eyebrow: "El primer paso",
      title: "Primera consulta, indispensable para nuevos clientes",
      body: "La primera consulta es un paso esencial para comenzar nuestro trabajo. Durante este encuentro inicial, recopilamos la información necesaria para comprender tu situación y establecer un plan personalizado. La consulta dura 1 hora y se realiza online por Zoom. Abordaremos tus dudas, alinearemos expectativas y trazaremos el mejor camino para alcanzar tus objetivos.",
      imageAlt: "Escultura espiritual blanca con un dragón entre las nubes",
      duration: "60 minutos",
      format: "Online por Zoom",
      action: "Reservar mi consulta",
    },
    about: {
      imageAlt: "Dani Therapies durante una sesión de cuidado energético",
      imageCaption: "Cura, guía y presencia para procesos energéticos y espirituales.",
      title: "Un trabajo sensible, con una estructura clara.",
      body: "La página principal presenta la esencia del trabajo, la primera consulta, algunos caminos posibles y el contacto. Las sesiones completas y los cursos tienen páginas propias, para que el sitio respire mejor y siga siendo fácil de navegar en móvil.",
      stats: [
        { title: "Online", text: "Sesiones por videollamada" },
        { title: "4 idiomas", text: "Portugués, inglés, español y neerlandés" },
        { title: "Acogida", text: "Escucha sensible y orientación espiritual" },
      ],
    },
    promptsTitle: "Quizás alguna de estas preguntas hable contigo",
    promptsIntro: "Cada proceso comienza con una pregunta sincera. Descubre qué camino se acerca a tu momento actual.",
    promptTones: ["Restauración", "Claridad", "Vínculo"],
    prompts: [
      "La restauración vibracional es esencial. Mantente alerta y protege tu energía.",
      "¿Qué cambios notarías en ti después de una restauración energética?",
      "Si tu querida mascota pudiera dejarte un mensaje, ¿cuál sería?",
      "Liberar a un ser querido que ya partió puede ser un acto de amor.",
      "¿Y si pudieras recibir un mensaje directo de tu Guía Espiritual?",
    ],
    services: {
      eyebrow: "Sesiones y valores",
      title: "Elige el cuidado que encaja con tu momento",
      intro: "Valores basados en las sesiones actuales. La confirmación final ocurre antes del pago, con Stripe preparado para euros.",
      action: "Reservar / pagar",
      items: esServices,
    },
    servicesPreview: {
      title: "Una vista previa de las sesiones",
      intro: "La página principal muestra solo algunos caminos. La lista completa tiene su propia página, con valores, duración y checkout preparado.",
      allLabel: "Ver todas las sesiones",
    },
    course: {
      eyebrow: "Curso online",
      title: "Ativação Sensorial (Classes em português)",
      intro: "Curso online para desarrollar la lectura sensorial mediante ejercicios de percepción, meditación, respiración y activación del cuerpo sensorial.",
      price: "285 €",
      duration: "6 semanas · inicio: 15/08/2026",
      cta: "Quiero inscribirme",
      formTitle: "Inscripción en el curso",
      name: "Nombre",
      age: "Edad",
      email: "Email",
      submit: "Continuar inscripción",
      paymentNote: "Stripe ya está preparado. Cuando se añadan las claves y Price IDs, este formulario enviará al checkout.",
      fallback: "Si el pago aún no está activo, la inscripción se envía por WhatsApp para que Dani dé seguimiento.",
    },
    coursePreview: {
      allLabel: "Ver cursos",
      note: "La inscripción separada mantiene la página principal más ligera.",
    },
    process: {
      eyebrow: "Cómo funciona",
      title: "Menos fricción, más claridad",
      steps: [
        ["01", "Elige sesión o curso", "La página muestra duración, valor y próximo paso sin páginas dispersas."],
        ["02", "Rellena solo lo necesario", "Curso: nombre, edad y email. Atención: conversación directa para confirmar el mejor camino."],
        ["03", "Paga con seguridad", "Stripe queda listo para tarjetas europeas y pagos en euros cuando la clienta envíe las claves."],
      ],
    },
    quote: "Cuidar la energía también es crear espacio para nuevas elecciones, nuevos sentidos y una vida más consciente.",
    blogPreview: {
      title: "Reflexiones de Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Ver blog completo",
    },
    contact: {
      eyebrow: "Hablemos",
      title: "¿Qué transformación buscas en este momento?",
      body: "Envía un mensaje breve. Será dirigido directamente al WhatsApp de Dani Therapies.",
      name: "Tu nombre",
      email: "Tu email",
      message: "¿Cómo podemos ayudarte?",
      submit: "Enviar por WhatsApp",
      privacy: "Tus datos no serán almacenados en este primer contacto.",
    },
    footer: {
      text: "Cuidado energético y espiritual con presencia, respeto y acogida.",
      rights: "Todos los derechos reservados.",
      disclaimer: "Las sesiones ofrecidas no sustituyen la atención médica, psicológica o de emergencia.",
      legal: {
        cookies: "Política de Cookies",
        terms: "Términos y Condiciones",
        privacy: "Política de Privacidad",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Hablar por WhatsApp",
  },
  nl: {
    metaTitle: "Energetische therapie en spirituele begeleiding",
    metaDescription: "Online sessies voor energetische zorg, spirituele begeleiding, cursussen en persoonlijke ontwikkeling bij Dani Therapies.",
    nav: { about: "Over", services: "Sessies", courses: "Cursussen", blog: "Inspiratie", contact: "Contact", book: "Sessie boeken" },
    hero: {
      eyebrow: "Energetische en spirituele zorg",
      title: "Een veilige ruimte om je energie te herstellen en naar je essentie te luisteren.",
      description: "Online sessies met aandacht, gevoeligheid en respect voor jouw moment.",
      primary: "Eerste consult boeken",
      secondary: "Bekijk de sessies",
      note: "Online · Zoom · Europa",
    },
    firstVisit: {
      eyebrow: "De eerste stap",
      title: "Eerste consult, essentieel voor nieuwe cliënten",
      body: "Het eerste consult is een essentiële stap om onze samenwerking te beginnen. Tijdens deze kennismaking verzamelen we de informatie die nodig is om jouw situatie te begrijpen en een persoonlijk plan op te stellen. Het consult duurt 1 uur en vindt online plaats via Zoom. We bespreken je vragen, stemmen verwachtingen af en bepalen samen de beste weg naar je doelen.",
      imageAlt: "Wit spiritueel beeld met een draak tussen de wolken",
      duration: "60 minuten",
      format: "Online via Zoom",
      action: "Mijn consult boeken",
    },
    about: {
      imageAlt: "Dani Therapies tijdens een energetische sessie",
      imageCaption: "Heling, begeleiding en aanwezigheid voor energetische en spirituele processen.",
      title: "Gevoelig werk met een duidelijke structuur.",
      body: "De hoofdpagina introduceert de essentie van het werk, het eerste consult, enkele mogelijke paden en contact. De volledige sessies en cursussen hebben eigen pagina's, zodat de site rustiger blijft en makkelijk te gebruiken is op mobiel.",
      stats: [
        { title: "Online", text: "Sessies via videogesprek" },
        { title: "4 talen", text: "Portugees, Engels, Spaans en Nederlands" },
        { title: "Aandacht", text: "Gevoelig luisteren en spirituele begeleiding" },
      ],
    },
    promptsTitle: "Misschien spreekt een van deze vragen je aan",
    promptsIntro: "Elk proces begint met een oprechte vraag. Ontdek welk pad past bij jouw huidige moment.",
    promptTones: ["Herstel", "Helderheid", "Verbinding"],
    prompts: [
      "Vibrationeel herstel is essentieel. Blijf bewust en bescherm je energie.",
      "Welke veranderingen zou je in jezelf merken na energetisch herstel?",
      "Als je geliefde huisdier je een boodschap kon nalaten, wat zou die zijn?",
      "Een dierbare die is heengegaan loslaten kan een daad van liefde zijn.",
      "Wat als je een directe boodschap van je Spirituele Gids kon ontvangen?",
    ],
    services: {
      eyebrow: "Sessies en prijzen",
      title: "Kies de zorg die nu bij je past",
      intro: "Prijzen zijn gebaseerd op de huidige beschikbare sessies. Definitieve bevestiging gebeurt vóór betaling, met Stripe voorbereid op euro's.",
      action: "Boeken / betalen",
      items: nlServices,
    },
    servicesPreview: {
      title: "Een preview van de sessies",
      intro: "De homepagina toont alleen enkele paden. De volledige lijst heeft een eigen pagina, met prijzen, duur en checkout voorbereid.",
      allLabel: "Bekijk alle sessies",
    },
    course: {
      eyebrow: "Online cursus",
      title: "Ativação Sensorial (Classes em português)",
      intro: "Online cursus om sensorisch lezen te ontwikkelen via waarnemingsoefeningen, meditatie, ademhaling en activatie van het sensorische lichaam.",
      price: "285 €",
      duration: "6 weken · start: 15/08/2026",
      cta: "Ik wil me inschrijven",
      formTitle: "Cursusinschrijving",
      name: "Naam",
      age: "Leeftijd",
      email: "E-mail",
      submit: "Inschrijving doorgaan",
      paymentNote: "Stripe is al voorbereid. Zodra sleutels en Price IDs zijn toegevoegd, stuurt dit formulier de persoon naar checkout.",
      fallback: "Als betaling nog niet actief is, wordt de inschrijving via WhatsApp verzonden zodat Dani kan opvolgen.",
    },
    coursePreview: {
      allLabel: "Bekijk cursussen",
      note: "Een aparte inschrijving houdt de hoofdpagina lichter.",
    },
    process: {
      eyebrow: "Hoe het werkt",
      title: "Minder frictie, meer duidelijkheid",
      steps: [
        ["01", "Kies een sessie of cursus", "De pagina toont duur, prijs en volgende stap zonder losse pagina's."],
        ["02", "Deel alleen wat nodig is", "Cursus: naam, leeftijd en e-mail. Sessie: direct gesprek om de beste route te bevestigen."],
        ["03", "Betaal veilig", "Stripe staat klaar voor Europese kaarten en betalingen in euro zodra de klant de sleutels stuurt."],
      ],
    },
    quote: "Voor je energie zorgen betekent ook ruimte maken voor nieuwe keuzes, nieuwe betekenis en een bewuster leven.",
    blogPreview: {
      title: "Inspiratie van Dani Therapies",
      quotePrefix: "“",
      quoteSuffix: "”",
      allLabel: "Bekijk alle inspiratie",
    },
    contact: {
      eyebrow: "Laten we praten",
      title: "Welke verandering zoek je op dit moment?",
      body: "Stuur een kort bericht. Het wordt rechtstreeks doorgestuurd naar Dani Therapies via WhatsApp.",
      name: "Je naam",
      email: "Je e-mail",
      message: "Hoe kunnen we helpen?",
      submit: "Verstuur via WhatsApp",
      privacy: "Je gegevens worden tijdens dit eerste contact niet opgeslagen.",
    },
    footer: {
      text: "Energetische en spirituele zorg met aandacht, respect en warmte.",
      rights: "Alle rechten voorbehouden.",
      disclaimer: "De aangeboden sessies vervangen geen medische, psychologische of spoedeisende zorg.",
      legal: {
        cookies: "Cookiebeleid",
        terms: "Algemene voorwaarden",
        privacy: "Privacybeleid",
        kvk: "KVK- 94756279",
      },
    },
    whatsapp: "Praat via WhatsApp",
  },
} as const;

export function getContent(locale: Locale) {
  return content[locale];
}
